[pytest]
testpaths = ./tests/unit
python_files = *_test.py
python_classes = Test*
python_functions = test_*
filterwarnings = 
  error
  ignore:UserWarning
  ignore:Function ham\(\) is deprecated:DeprecationWarning
log_cli = true